<a href="https://colab.research.google.com/github/bencode/tfadv/blob/main/Gradient_Tape_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones((2, 2))
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
with tf.GradientTape() as t:
  t.watch(x)
  y = tf.reduce_sum(x)
  z = tf.square(y)
dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [5]:
print(y)

tf.Tensor(4.0, shape=(), dtype=float32)


In [6]:
x = tf.constant(3.0)
with tf.GradientTape() as t:
  t.watch(x)
  y = x * x
  z = y * y

dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(108.0, shape=(), dtype=float32)


In [9]:
x = tf.constant(3.0)
with tf.GradientTape(persistent=True) as t:
  t.watch(x)
  y = x * x
  z = y * y

dz_dx = t.gradient(z, x)
print(dz_dx)

dy_dx = t.gradient(y, x)
print(dy_dx)

del t

tf.Tensor(108.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [13]:
x = tf.Variable(1.0)
with tf.GradientTape() as t2:
  with tf.GradientTape() as t1:
    y = x * x * x
    dy_dx = t1.gradient(y, x)
d2y_dx2 = t2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [14]:
x = tf.Variable(1.0)

with tf.GradientTape() as t2:
  with tf.GradientTape() as t1:
    y = x * x * x
  dy_dx = t1.gradient(y, x)   # outer
d2y_dx2 = t2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [15]:
x = tf.Variable(1.0)

with tf.GradientTape() as t2:
  with tf.GradientTape() as t1:
    y = x * x * x

dy_dx = t1.gradient(y, x)   # outer outer
d2y_dx2 = t2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
None


In [16]:
x = tf.Variable(1.0)

with tf.GradientTape() as t2:
  with tf.GradientTape() as t1:
    y = x * x * x

    dy_dx = t1.gradient(y, x)
    d2y_dx2 = t2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [17]:
x = tf.Variable(1.0)

with tf.GradientTape() as tape_2:
    with tf.GradientTape() as tape_1:
        y = x * x * x

        dy_dx = tape_1.gradient(y, x)
        
# this is also acceptable
d2y_dx2 = tape_2.gradient(dy_dx, x)

print(dy_dx)
print(d2y_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
